console.log("*".repeat(5));
console.log("*".repeat(25));
console.log("*".repeat(45));
console.log("*".repeat(65));
console.log("*".repeat(85));
console.log("*".repeat(65));
console.log("*".repeat(45));
console.log("*".repeat(25));
console.log("*".repeat(5));